platform :ios, '7.0'
xcodeproj 'MasterPass'
source 'https://github.com/CocoaPods/Specs.git'

pod 'ObjectiveSugar'
pod 'KLScrollSelect', :git => 'https://github.com/DavidBenko/KLScrollSelect.git', :branch => 'full-feature'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'pop', '~> 1.0'
pod 'BlocksKit'
pod 'SVWebViewController', :head
pod 'SIAlertView', :git => 'https://github.com/AnyPresence-Services/SIAlertView.git', :branch => 'mc_setup'
pod 'FontAwesomeKit', '~> 2.1.0'
pod 'JMGBlockSegue'
pod 'M13Checkbox', :git => 'https://github.com/Marxon13/M13Checkbox'
pod 'BButton'
pod 'Masonry', :git => 'https://github.com/Masonry/Masonry.git'
pod 'SwipeView'
pod 'TPKeyboardAvoiding'
pod 'BBBadgeBarButtonItem'
pod 'MBProgressHUD', '~> 0.8'
pod 'UpdateAutoLayoutConstraints'
pod 'AFNetworking', '~> 2.0'
pod 'XMLDictionary'